[workspace]
resolver="2"
members = [
    ".",
    "examples/sqlx-example/",
    "examples/NoPoolType/",
    "examples/surrealdb/",
]

[package]
name = "axum_session_auth"
version = "0.10.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a User Authentication and privilege Token Checks. It requires the Axum_Session library."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/axum_session_auth"
keywords = ["Axum", "Tower", "SQLx", "Session", "Authentication"]
repository = "https://github.com/AscendingCreations/AxumSessionAuth"

[features]
default = ["postgres-rustls", "advanced"]
sqlite-rustls = ["axum_session/sqlite-rustls"]
sqlite-native = ["axum_session/sqlite-native"]
postgres-rustls = ["axum_session/postgres-rustls"]
postgres-native = ["axum_session/postgres-native"]
mysql-rustls = ["axum_session/mysql-rustls"]
mysql-native = ["axum_session/mysql-native"]
redis-db = ["axum_session/redis-db"]
redis-clusterdb = ["axum_session/redis-clusterdb"]
surreal =  ["axum_session/surreal"]
key-store = ["axum_session/key-store"]
rest_mode = ["axum_session/rest_mode"]
mongo = ["axum_session/mongo"]
advanced = ["axum_session/advanced"]

[dependencies]
axum-core = "0.4.0"
async-trait = "0.1.73"
anyhow = "1.0.75"
async-recursion = "1.0.5"
http = "1.0.0"
tower-layer = "0.3.2"
tower-service = "0.3.2"
futures = "0.3.28"
bytes = "1.5.0"
http-body = "1.0.0"
dashmap = "5.5.3"
chrono = { version = "0.4.28", default-features = false, features = ["clock", "serde", "std"] }
tokio = { version = "1.34.0", features = ["full"] }
serde = "1.0.192"

[dependencies.axum_session]
#path = "C:/Sources/AxumSession"
#git = "https://github.com/AscendingCreations/AxumSessions.git"
#branch = "axum0.6"
version = "0.10.0"
default-features = false

[package.metadata.docs.rs]
features = ["sqlite-rustls","mysql-rustls","redis-db", "surreal", "advanced"]
rustdoc-args = ["--document-private-items"]
