[package]
name = "axum_sqlx_session_auth"
version = "0.2.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a User Authentication and privilege Token Checks. It requires the AxumSQLxSessions library and Tower_cookies library."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_sqlx_session_auth"
keywords = ["Axum", "Tower", "SQLx", "Session", "Authentication"]
repository = "https://github.com/AscendingCreations/axum_sqlx_session_auth"

[dependencies]
axum = "0.4"
tokio = { version = "1", features = ["full"] }
async-trait = "0.1"
axum_sqlx_sessions = { git = "https://github.com/AscendingCreations/AxumSqlxSessions.git", branch = "anytype" }
sqlx = { git = "https://github.com/genusistimelord/sqlx.git", branch = "AnyConnectionKindPublic", features = [
    "runtime-tokio-rustls",
    "chrono",
    "json",
    "all-types",
] }
anyhow = "1.0"
async-recursion = "1.0"
