[workspace]
members = [
    ".",
    "example",
]

[package]
name = "axum_session_auth"
version = "0.1.1"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a User Authentication and privilege Token Checks. It requires the Axum_Session library."
edition = "2021"
license = "MIT OR Apache-2.0"
readme = "README.md"
documentation = "https://docs.rs/axum_session_auth"
keywords = ["Axum", "Tower", "SQLx", "Session", "Authentication"]
repository = "https://github.com/AscendingCreations/AxumSessionsAuth"

[features]
default = ["postgres-rustls"]
sqlite-rustls = ["axum_session/sqlite-rustls"]
sqlite-native = ["axum_session/sqlite-native"]
postgres-rustls = ["axum_session/postgres-rustls"]
postgres-native = ["axum_session/postgres-native"]
mysql-rustls = ["axum_session/mysql-rustls"]
mysql-native = ["axum_session/mysql-native"]
redis-db = ["axum_session/redis-db"]
surrealdb-rocksdb =  ["axum_session/surrealdb-rocksdb"]
surrealdb-tikv =  ["axum_session/surrealdb-tikv"]
surrealdb-indxdb =  ["axum_session/surrealdb-indxdb"]
surrealdb-fdb-5_1 =  ["axum_session/surrealdb-fdb-5_1"]
surrealdb-fdb-5_2 =  ["axum_session/surrealdb-fdb-5_2"]
surrealdb-fdb-6_0 =  ["axum_session/surrealdb-fdb-6_0"]
surrealdb-fdb-6_1 =  ["axum_session/surrealdb-fdb-6_1"]
surrealdb-fdb-6_2 =  ["axum_session/surrealdb-fdb-6_2"]
surrealdb-fdb-6_3 =  ["axum_session/surrealdb-fdb-6_3"]
surrealdb-fdb-7_0 =  ["axum_session/surrealdb-fdb-7_0"]
surrealdb-fdb-7_1 =  ["axum_session/surrealdb-fdb-7_1"]
surrealdb-mem =  ["axum_session/surrealdb-mem"]

[dependencies]
axum-core = "0.3.2"
async-trait = "0.1.66"
anyhow = "1.0.69"
async-recursion = "1.0.2"
http = "0.2.9"
tower-layer = "0.3.2"
tower-service = "0.3.2"
futures = "0.3.26"
bytes = "1.4.0"
http-body = "0.4.5"
dashmap = "5.4.0"
chrono = { version = "0.4.24", features = ["clock", "serde", "std"] }
tokio = { version = "1.26.0", features = ["full"] }
serde = "1.0.155"

[dependencies.axum_session]
#path = "D:/Sources/AxumSessions"
#git = "https://github.com/AscendingCreations/AxumSessions.git"
#branch = "axum0.6"
version = "0.1.0"
default-features = false

[package.metadata.docs.rs]
features = ["postgres-rustls"]
