[package]
name = "axum_sessions_auth"
version = "1.4.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a User Authentication and privilege Token Checks. It requires the Axum_Database_Sessions library."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_sessions_auth"
keywords = ["Axum", "Tower", "SQLx", "Session", "Authentication"]
repository = "https://github.com/AscendingCreations/AxumSessionsAuth"

[features]
default = ["postgres", "rustls"]
sqlite = ["axum_database_sessions/sqlite"]
postgres = ["axum_database_sessions/postgres"]
mysql = ["axum_database_sessions/mysql"]
rustls = ["axum_database_sessions/rustls"]
native-tls = ["axum_database_sessions/native-tls"]

[dependencies]
axum-core = "0.2.4"
async-trait = "0.1.53"
anyhow = "1.0.57"
async-recursion = "1.0.0"
http = "0.2.7"
tower-layer = "0.3.1"
tower-service = "0.3.1"
futures = "0.3.21"
bytes = "1.1.0"
http-body = "0.4.4"

[dependencies.axum_database_sessions]
#git = "https://github.com/AscendingCreations/AxumSessions.git"
#rev = "f3f6565"
#branch = "gdpr"
version = "2.0.0"
default-features = false

[package.metadata.docs.rs]
features = ["postgres", "rustls"]
