[package]
name = "axum_sessions_auth"
version = "4.0.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a User Authentication and privilege Token Checks. It requires the Axum_Database_Sessions library."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_sessions_auth"
keywords = ["Axum", "Tower", "SQLx", "Session", "Authentication"]
repository = "https://github.com/AscendingCreations/AxumSessionsAuth"

[features]
default = ["postgres-rustls"]
sqlite-rustls = ["axum_database_sessions/sqlite-rustls"]
sqlite-native = ["axum_database_sessions/sqlite-native"]
postgres-rustls = ["axum_database_sessions/postgres-rustls"]
postgres-native = ["axum_database_sessions/postgres-native"]
mysql-rustls = ["axum_database_sessions/mysql-rustls"]
mysql-native = ["axum_database_sessions/mysql-native"]
redis-db = ["axum_database_sessions/redis-db"]

[dependencies]
axum-core = "0.3.0-rc.1"
async-trait = "0.1.57"
anyhow = "1.0.60"
async-recursion = "1.0.0"
http = "0.2.8"
tower-layer = "0.3.1"
tower-service = "0.3.2"
futures = "0.3.23"
bytes = "1.2.1"
http-body = "0.4.5"
dashmap = "5.3.4"
chrono = { version = "0.4.20", features = ["clock", "serde", "std"] }
tokio = { version = "1.20.1", features = ["full"] }
serde = "1.0.144"

[dependencies.axum_database_sessions]
#path = "User:/Sources/AxumSessions"
git = "https://github.com/AscendingCreations/AxumSessions.git"
branch = "state"
version = "4.1.0"
default-features = false

[package.metadata.docs.rs]
features = ["postgres-rustls"]
