[package]
name = "axum_session_auth"
version = "0.2.0"
authors = ["Andrew Wheeler <genusistimelord@gmail.com>"]
description = "Library to Provide a User Authentication and privilege Token Checks. It requires the AxumSessions library and Tower_cookies library."
edition = "2021"
license = "MIT"
readme = "README.md"
documentation = "https://docs.rs/axum_session_auth"
keywords = ["Axum", "Tower", "SQLx", "Session", "Authentication"]
repository = "https://github.com/AscendingCreations/axum_session_auth"

[features]
default = ["postgres"]
sqlite = ["sqlx/sqlite", "axum_database_sessions/sqlite"]
postgres = ["sqlx/postgres", "axum_database_sessions/postgres"]
mysql = ["sqlx/mysql", "axum_database_sessions/mysql"]

[dependencies]
axum = "0.4"
tokio = { version = "1.15.0", features = ["full"] }
async-trait = "0.1"
axum_database_sessions = { path = "../AxumSessions" }
sqlx = { version = "0.5.10", features = [
    "runtime-tokio-native-tls",
    "chrono",
    "json",
    "all-types",
] }
anyhow = "1.0"
async-recursion = "1.0"
